### ISSUE TITLE
[BUG] Font color is black

### ISSUE THREAD

**Issue by kg-currenxie** [apilylabs/ophiuchi-desktop#13]
I just downloaded Version 0.5.0 (20240604.120244) and started it on MacOS

![image](https://github.com/apilylabs/ophiuchi-desktop/assets/48229166/e8fc67ce-52f9-441e-9070-23226c398220)

i can select all text to reveal it
![image](https://github.com/apilylabs/ophiuchi-desktop/assets/48229166/8b900ce1-8333-4634-8bb6-bf474d76a96d)

this screen seems fine:
![image](https://github.com/apilylabs/ophiuchi-desktop/assets/48229166/2163e7fe-88dc-4e6c-8962-38b697b92ab6)

**Comment by cheeselemon** [comment]
It's been fixed on [0.5.0](https://github.com/apilylabs/ophiuchi-desktop/releases/tag/0.5.0)!

Can you download 0.5.0 and confirm? 

Thanks!

**Comment by cheeselemon** [comment]
@kg-currenxie I've released 0.5.1 and it should be fixed!

**Comment by kg-currenxie** [comment]
Works! :)
The app name is now `Ophiuchi 2.app`, but maybe that's on purpose :)
Thanks

**Comment by cheeselemon** [comment]
Great. As a side note, if you unzip a file in the folder where a same file name exist, macOS will automatically add numbers! @kg-currenxie

**Comment by kg-currenxie** [comment]
Ah, i'm stupid :D thanks
